### ISSUE TITLE
PX4 v1.9.0 NOT GIVING SERVO OUTPUTS ON Cuav5+

### ISSUE THREAD

**Issue by vineethtom** [PX4/PX4-Bootloader#196]
No servo outputs and Starting PX4IO beep continously while flashing pixhawk v1.9.0.

Tried using V1.11 which works perfectly.
Since I am working on fixed wings and also need a HiL environment for the same, I have to stick on to V1.9.0.

Could someone help me ASAP.

my mail id is vineethinside@gmail.com.

Its bugging my head for a long time now

I am relatively new to pixhawk.

**Comment by LorenzMeier** [comment]
CUAV v5 is not really supported in 1.9 - are you sure that HIL is not working in 1.11? If so, please file an issue in PX-Autopilot, not here

**Comment by vineethtom** [comment]
So are you saying that V1.9.0 would work on CuAV v5+?

Hil support for fixed wings in 1.11.0 is not there.

**Comment by vineethtom** [comment]
Correction: Are you saying 1.9.0 doesnt work on Cuav v5+?

**Comment by LorenzMeier** [comment]
Please comment on this issue and share what you're exactly seeing. HITL is supported for fixed wing aircraft with autostart ID 1000, so I'm not quite sure where it breaks for you.

https://github.com/PX4/PX4-Autopilot/issues/17410

I will not continue to respond here, because this is the bootloader repository.
